name: Nightly Trigger

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - name: Invoke workflow
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Haskell CI
        token: ${{ secrets.MACHINE_TOKEN }}
        inputs: '{ "reason": "nightly", "tests": "all" }'
